# Generated by Django 5.1.1 on 2024-10-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"]},
        ),
    ]
